spring:
  application:
    name: gateway # 服务名称
  cloud:
    gateway:
      routes: # 网关路由配置
        - id: user-service # 路由id，自定义，只要唯一即可
          uri: lb://userservice # lb 是负载均衡
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/** # 这个是按照路径匹配，只要以/user/开头就符合要求
eureka:
  client:
    service-url: #eureka的地址信息
      defaultZone: http://127.0.0.1:10085/eureka
server:
  port: 10010 # 网关端口
